Feature/21
shimotaroo/Yanbaru-Qiita-App-sample pull request #42
Opened 2021-03-14 17:51 UTC by yoshitaro-yoyo

Closes #21

【追加】
・記事検索用クエリ生成メソッドをモデルに分割
・記事検索用メソッド
・記事検索時の「¥ _ %」文字列エスケープ処理
・config内に定数用のディレクトリ、期生セレクトボックス用の配列ファイル作成
・articles/index.blade.php → ページネート時の検索条件・検索結果の保持
・layouts/search.blade.php → 検索結果の表示時 セレクトボックス・入力フォーム検索条件保持

【変更】
なし

【特記事項】
検索条件は全部で7＋1（全件取得）つ設定しました。
①Term
②　　　 Category
③ 　　　　　　　     Word 
④Term・Category
⑤Term　　　　　　 Word 
⑥　　　 Category・Word 
⑦Term・Category・Word 　が選択されていた場合

それぞれの条件下での検索結果表示・検索条件保持(検索結果画面遷移時・ページネート時)の動作確認は問題なかったと思いますが、確認お願いしたいと思います！

2021-03-15 00:31 UTC, shimotaroo requested changes
レビューしました！

ガッツリレビューしましたww
修正お願いします！🙇‍♂️

あと、意味不明なところは気を使わず聞いてくださいね🙇‍♂️

2021-03-15 00:31 UTC, shimotaroo commented on app/Http/Controllers/ArticleController.php
> +        $query = $article->getQuery();
oh...スーパーファットコントローラー発見ですねww
145〜182行はモデルに移しましょうかね！

ここ結構修正多いです。

1. まず、見た感じですがgetQueryメソッドを独立させる必要はありません。
2. SQLを作っていくところ（148〜179）ですが、ここはif文3つで書けます。ヒントは「リクエスト（クエリーパラメータ）がないならスルー、あるならSQLに条件を追加する」です。Term、Category、Wordで１つずつif文を書くだけですね。わからなかったらもう少し解説しますので言ってください！（これ、ヒントにはなります→https://github.com/shimotaroo/laravel-app/blob/master/app/Article.php）

2021-03-15 00:31 UTC, shimotaroo commented on config/consts/term.php
> +<?php
今回はこれでOKですが、テーブル数少ない＆定数定義も少ないので`config/const.php`に書くのが良いかもですね！

これから長く使っていく可能性もあるので修正して欲しいですm(__)m
申し訳ないです...

※好みの問題なので間違ってないのでご理解ください...

2021-03-15 00:31 UTC, shimotaroo commented on config/consts/term.php
> +    return [
search.blade.phpで1つoptionタグを入れていましたが、
ここに
`'' => ''`
を追加してあげれば解決しますよ！

2021-03-15 00:31 UTC, shimotaroo commented on resources/views/layouts/search.blade.php
> +    {{ csrf_field() }}
これが今回の修正で一番アカンやつですね...ww

GETパラメータなので不要です！かつ、検索かけた時にCSRFトークンもURLのクエリパラメータとして追加されているので情報ダダ漏れですww

CSRFトークンをPOSTやPUTなど認証と認可が必要な場合にのみ使います。

ちなみに
```
@csrf
```
でも追加できます！

![スクリーンショット 2021-03-15 9 28 23](https://user-images.githubusercontent.com/58982088/111089822-d1f11080-8570-11eb-8dc3-ab6a0640ca70.png)

2021-03-15 00:31 UTC, shimotaroo commented on resources/views/layouts/search.blade.php
> +                    <option></option>
このoptionタグは消しましょう！
configの方のコメント通りです！

2021-03-15 00:31 UTC, shimotaroo commented on resources/views/layouts/search.blade.php
> +                        <option value="{{ $termNumber }}" @if(old('term', $selectTerm ?? '') == $index) selected @endif>{{ $termNumber }}</option>
この書き方、初めて見ました！！
いいですね！
ここだけ簡単にQiitaにまとめて欲しいです！！笑

2021-03-15 00:31 UTC, shimotaroo commented on routes/web.php
> +Route::get('searchArticles','ArticleController@searchArticles')->name('searchArticles');
ここはArticle関係なので24行目に書きましょう！

他の修正もあるのでここは答え（例）を書きます。

```
Route::get('articles/search','ArticleController@search')->name('articles.search');
```
これに修正ください！！

```
$ php artisan route:list
```
でルーティング一覧が確認できます。おそらく今のだとここだけ明らかに規則が違うのでなるべく他と合わせるようにすると良いですね！

2021-03-15 00:31 UTC, shimotaroo commented on resources/views/layouts/search.blade.php
> +                    <option></option>
ここも無くしたいですね...
これは僕の方で考えますのでいったんこのままでいきましょう！！

2021-03-15 01:12 UTC, shimotaroo commented
【追加】

`.DS_Store`が差分として入ってしまっていますので削除しておいてください！
（これも無駄な修正となります）

2021-03-15 02:06 UTC, yoshitaro-yoyo commented on app/Article.php
> +
どちらも行う様にします！
ありがとうございます(*^^*)

2021-03-16 11:16 UTC, yoshitaro-yoyo commented on app/Http/Controllers/ArticleController.php
> +        $categoryForSelects = $category->getAll();
`$categoryForSelectBox`

2021-03-16 11:16 UTC, yoshitaro-yoyo commented on app/Http/Controllers/ArticleController.php
> +    public function searchArticles(Request $request)
`search`に修正しました！

2021-03-16 11:17 UTC, yoshitaro-yoyo commented on config/consts/term.php
> +<?php
`config/const.php`のディレクトリ構造に変更しました！

2021-03-16 11:24 UTC, yoshitaro-yoyo commented on resources/views/layouts/search.blade.php
> +    {{ csrf_field() }}
申し訳ないです！URLにtoken出ているのを視認していたのですが…
以下の記述のみに変更したらURLに表示されなくなったのですがこれで良いのでしょうか？
`<form action="{{ route('articles.search') }}">`

![スクリーンショット 2021-03-16 20 23 22](https://user-images.githubusercontent.com/69310368/111301361-79676380-8695-11eb-90fb-92aca9ad5b1b.png)

2021-03-16 15:20 UTC, shimotaroo requested changes
レビューしました！
もう少しです！！！！
ファイトっす！！！

2021-03-16 15:20 UTC, shimotaroo commented on app/Http/Controllers/ArticleController.php
> +        $Article = new Article;
ここ小文字でいいかと。
上の
```
$category = new Category();
```
と合ってないです！

2021-03-16 15:20 UTC, shimotaroo commented on app/Http/Controllers/ArticleController.php
> +        $articles = $allArticlesBySearch->paginate(10);
ここまで全部モデルに移しましょう！
（前のコメントで僕ここまで指示してなかったらすみません）

せっかくModelに処理を写したので肝心のDBへの接続がControllerにあるのは超違和感です！

```
$article = new Article();
$searchedArticles = $article->getBySearchParameters($inputTerm, $inputCategory, $inputWord);
```
とかですかね〜

メソッド名は`->getBySearchParameters()`か`->getBySearchInput()`か、ですかね

2021-03-16 15:20 UTC, shimotaroo commented on routes/web.php
> +Route::get('articles.search', 'ArticleController@search')->name('articles.search');
ここURLの設定おかしいですね〜！

```
Route::get('/articles/search', 'ArticleController@search')->name('articles.search');
```
ですかね。

ただ、このURLだとここに書くとエラーになるかもです...
23行目に書かないといけないかもです...
試してみてください！

2021-03-16 15:52 UTC, yoshitaro-yoyo commented on routes/web.php
> +Route::get('articles.search', 'ArticleController@search')->name('articles.search');
![スクリーンショット 2021-03-17 0 51 54](https://user-images.githubusercontent.com/69310368/111339271-f953f480-86ba-11eb-83b7-beba7fe52e69.png)


![スクリーンショット 2021-03-17 0 51 29](https://user-images.githubusercontent.com/69310368/111339207-eb9e6f00-86ba-11eb-8757-a50d17035b23.png)

2021-03-16 16:22 UTC, yoshitaro-yoyo commented on app/Http/Controllers/ArticleController.php
> +        $articles = $allArticlesBySearch->paginate(10);
```$article = new Article();
$searchedArticles = $article->getBySearchParameters($inputTerm, $inputCategory, $inputWord);```
このコードはcontrollerに記載する用のコードとして記載してくださったのでしょうか？

加藤　鉄良  11 minutes ago
であれば
$searchedArticles
をviewに渡さなくてはいけません。
その場合、複数のbladeの変数名を変更しなくてはいけなくなります。
$article 
を複数のviewで使用していますが、この２つの変数の内容は同じです。
またcontrollerでの記述を
$article = new Article();
$query = $article->query();
$searchedArticles = $article->getBySearchParameters($query, $inputTerm, $inputCategory, $inputWord);
にしなければ怒られます。
Symfony\Component\Debug\Exception\FatalThrowableError
Too few arguments to function App\Article::getBySearchParameters(), 3 passed in /var/www/html/app/Http/Controllers/ArticleController.php on line 152 and exactly 4 expected
モデル側のメソッドの引数が4に対してcontroller側で3つしか指定していないからですが、引数だけ修正しても$queryに対する未定義エラーが返ってきます:thinking_face:
なので
$query = $article->query();
の記述は必要かと思うのですが、そもそも自分が何か勘違してしまっているのでしょうか？ (edited)

2021-03-17 23:52 UTC, shimotaroo approved these changes
一旦マージします！
お疲れ様でした！！

2021-03-17 23:52 UTC, merged